#[cfg(test)]
mod tests {
    use crate::commands;
    use specta_typescript::Typescript;
    use tauri_specta::collect_commands;

    #[test]
    fn generate_bindings() {
        let builder = tauri_specta::Builder::<tauri::Wry>::new().commands(collect_commands![
            // Products
            commands::get_products,
            commands::get_product_by_id,
            commands::get_product_by_barcode,
            commands::search_products,
            commands::get_low_stock_products,
            commands::create_product,
            commands::update_product,
            commands::delete_product,
            commands::deactivate_product,
            commands::reactivate_product,
            commands::get_all_products,
            commands::get_inactive_products,
            // Categories
            commands::get_categories,
            commands::get_categories_with_count,
            commands::get_category_by_id,
            commands::create_category,
            commands::update_category,
            commands::delete_category,
            commands::deactivate_category,
            commands::reactivate_category,
            commands::get_all_categories,
            commands::get_inactive_categories,
            // Employees
            commands::get_employees,
            commands::get_employee_by_id,
            commands::authenticate_by_pin,
            commands::authenticate_employee,
            commands::has_admin,
            commands::create_first_admin,
            commands::has_any_employee,
            commands::create_employee,
            commands::update_employee,
            commands::deactivate_employee,
            commands::reactivate_employee,
            commands::logout,
            commands::get_current_user,
            commands::get_inactive_employees,
            // Sales
            commands::get_sales,
            commands::get_sales_today,
            commands::get_today_sales,
            commands::get_sale_by_id,
            commands::get_sales_by_session,
            commands::create_sale,
            commands::cancel_sale,
            commands::get_daily_summary,
            commands::get_daily_sales_total,
            commands::get_monthly_summary,
            // Cash
            commands::get_current_session,
            commands::get_current_cash_session,
            commands::get_session_history,
            commands::get_cash_session_history,
            commands::get_session_movements,
            commands::open_cash_session,
            commands::close_cash_session,
            commands::add_cash_movement,
            commands::get_cash_session_summary,
            // Stock
            commands::get_recent_stock_movements,
            commands::get_product_stock_movements,
            commands::create_stock_movement,
            commands::get_product_lots,
            commands::get_expiring_lots,
            commands::get_expired_lots,
            // Suppliers
            commands::get_suppliers,
            commands::get_supplier_by_id,
            commands::search_suppliers,
            commands::create_supplier,
            commands::update_supplier,
            commands::delete_supplier,
            commands::deactivate_supplier,
            commands::reactivate_supplier,
            commands::get_all_suppliers,
            commands::get_inactive_suppliers,
            // Customers
            commands::get_customers,
            commands::get_customers_paginated,
            commands::get_customer_by_id,
            commands::get_customer_by_cpf,
            commands::search_customers,
            commands::create_customer,
            commands::update_customer,
            commands::deactivate_customer,
            commands::reactivate_customer,
            commands::get_customer_vehicles,
            commands::get_customer_vehicle_by_id,
            commands::create_customer_vehicle,
            commands::update_customer_vehicle,
            commands::deactivate_customer_vehicle,
            commands::update_vehicle_km,
            // Settings
            commands::get_all_settings,
            commands::get_settings_by_group,
            commands::get_setting,
            commands::get_setting_bool,
            commands::get_setting_number,
            commands::set_setting,
            commands::delete_setting,
            // Vehicles
            commands::get_vehicle_brands,
            commands::get_vehicle_brand_by_id,
            commands::create_vehicle_brand,
            commands::get_vehicle_models,
            commands::get_vehicle_model_by_id,
            commands::create_vehicle_model,
            commands::get_vehicle_years,
            commands::get_vehicle_year_by_id,
            commands::create_vehicle_year,
            commands::search_vehicles,
            commands::get_complete_vehicle,
            commands::get_product_compatibilities,
            commands::add_product_compatibility,
            commands::remove_product_compatibility,
            commands::save_product_compatibilities,
            commands::get_products_by_vehicle,
            // Reports
            commands::get_stock_report,
            commands::get_top_products,
            commands::get_sales_report,
            commands::get_financial_report,
            commands::get_employee_performance,
            commands::get_motoparts_dashboard_stats,
            commands::get_service_order_stats,
            commands::get_top_products_motoparts,
            // Alerts
            commands::get_alerts,
            commands::get_unread_alerts,
            commands::get_unread_alert_count,
            commands::get_unread_alerts_count,
            commands::mark_alert_read,
            commands::mark_all_alerts_read,
            commands::create_alert,
            commands::delete_alert,
            // Price History
            commands::get_price_history_by_product,
            commands::get_recent_price_history,
            commands::get_price_history_by_id,
            // System
            commands::get_app_data_path,
            commands::get_database_path,
            commands::get_disk_usage,
            commands::fix_firewall_rules,
            // Service Orders
            commands::get_open_service_orders,
            commands::get_service_orders_paginated,
            commands::get_service_order_by_id,
            commands::get_service_order_by_number,
            commands::get_service_order_details,
            commands::create_service_order,
            commands::update_service_order,
            commands::start_service_order,
            commands::complete_service_order,
            commands::deliver_service_order,
            commands::cancel_service_order,
            commands::finish_service_order,
            commands::get_service_order_items,
            commands::add_service_order_item,
            commands::remove_service_order_item,
            commands::update_service_order_item,
            commands::get_services,
            commands::get_service_by_id,
            commands::get_service_by_code,
            commands::create_service,
            commands::update_service,
            commands::get_vehicle_services_history,
            // Warranties
            commands::get_active_warranties,
            commands::get_warranties_paginated,
            commands::get_warranty_by_id,
            commands::get_warranty_details,
            commands::get_warranties_by_customer,
            commands::get_warranties_by_product,
            commands::create_warranty_claim,
            commands::update_warranty_claim,
            commands::approve_warranty,
            commands::deny_warranty,
            commands::get_warranty_stats,
            // Hardware
            commands::list_serial_ports,
            commands::list_hardware_ports,
            commands::check_port_exists,
            commands::configure_printer,
            commands::print_receipt,
            commands::print_sale_by_id,
            commands::print_service_order,
            commands::test_printer,
            commands::test_printer_connection,
            commands::print_test_documents,
            commands::get_printer_config,
            commands::configure_scale,
            commands::load_hardware_configs,
            commands::hardware_health_check,
            commands::read_weight,
            commands::read_scale_weight,
            commands::test_scale_connection,
            commands::auto_detect_scale,
            commands::get_scale_config,
            commands::configure_drawer,
            commands::open_drawer,
            commands::open_cash_drawer,
            commands::get_drawer_config,
            commands::start_scanner_server,
            commands::start_serial_scanner,
            commands::stop_scanner_server,
            commands::list_scanner_devices,
            commands::get_scanner_server_info,
            commands::generate_pairing_qr,
            commands::generate_qr_svg,
            // Backups
            commands::backup::create_backup,
            commands::backup::restore_backup,
            commands::backup::list_backups,
            commands::backup::cleanup_old_backups,
            commands::backup::upload_backup_to_drive,
            commands::backup::download_backup_from_drive,
            commands::backup::list_drive_backups,
            commands::backup::exchange_google_code,
            commands::backup::get_google_auth_url,
            commands::backup::list_cloud_backups_cmd,
            commands::backup::upload_cloud_backup_cmd,
            commands::backup::get_cloud_backup_cmd,
            commands::backup::delete_cloud_backup_cmd,
            // Network
            commands::network::start_network_client,
            commands::network::stop_network_client,
            commands::network::get_network_status,
            // Mobile
            commands::start_mobile_server,
            commands::stop_mobile_server,
            commands::get_mobile_server_info,
            commands::get_mobile_server_status,
            commands::get_connected_devices,
            commands::disconnect_mobile_device,
            // License
            commands::get_hardware_id,
            commands::activate_license,
            commands::validate_license,
            commands::get_stored_license,
            commands::sync_metrics,
            commands::get_server_time,
            commands::restore_license,
            commands::update_license_admin,
            commands::recover_license_from_login,
            commands::license_server_login,
        ]);

        builder
            .export(
                Typescript::default().header("// @ts-nocheck\n/* eslint-disable */"),
                "../src/lib/bindings.ts",
            )
            .expect("Failed to export typescript bindings");
    }
}
