-- E2E Test Seed Data
-- This file seeds TEST DATA only (not schema - that's handled by migrations)

-- Wait for tables to exist (migrations run independently)
-- argon2id hash for "testpassword123" (generated by backend)
INSERT INTO admins (id, email, password_hash, name, company_name, is_active, is_verified)
VALUES (
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'e2e-test@giro.com.br',
    '$argon2id$v=19$m=19456,t=2,p=1$hISwBty4YKlyFrEfWEwAgg$otS+OIctqwsdxkgIouzLpvUqL6Ok6chLnVZZ6ElRLUc',
    'E2E Test Admin',
    'E2E Test Company',
    TRUE,
    TRUE
) ON CONFLICT (email) DO NOTHING;

-- Insert a test license for the admin
INSERT INTO licenses (id, license_key, admin_id, plan_type, status)
VALUES (
    'b0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22',
    'E2E-TEST-LICENSE-KEY',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'annual',
    'pending'
) ON CONFLICT (license_key) DO NOTHING;
