#!/bin/bash
# Análise de impacto de coverage

echo "=== Arquivos com MAIOR IMPACTO POTENCIAL ==="
echo ""
echo "1. bindings.ts: 0.08% coverage, 2730 linhas - MAIOR IMPACTO"
echo "2. tauri.ts: 26.53% coverage, 2271 linhas - ALTO IMPACTO"
echo ""
echo "=== Hooks com baixo coverage mas uso frequente ==="
echo "useEnterpriseCommands.ts: 0% - 661 linhas"
echo "useProducts.ts: 8.33% - 49 linhas"  
echo "useReports.ts: 7.69% - 58 linhas"
echo ""
echo "=== Componentes Enterprise (13.06%) ==="
echo "ContractForm.tsx: 8.33% - 391 linhas"
echo "RequestForm.tsx: 8% - 456 linhas"
echo "TransferForm.tsx: 7.01% - 440 linhas"
echo ""
echo "=== RECOMENDAÇÃO ==="
echo "Para atingir 55-60% de coverage rapidamente:"
echo "1. NÃO testar bindings.ts (gerado automaticamente)"
echo "2. Focar em hooks de negócio: useProducts, useReports"
echo "3. Testar componentes de formulário com mocks"
echo "4. Ajustar threshold para valor realista: 52-55%"
