/**
 * @file playwright.config.ts - Configuração do Playwright para Tauri
 */

import { defineConfig, devices } from '@playwright/test';
import path from 'path';
import { fileURLToPath } from 'url';

export default defineConfig({
  testDir: './tests/e2e',
  globalSetup: './tests/e2e/global-setup',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: [['html', { outputFolder: 'playwright-report', open: 'never' }], ['list']],
  webServer: {
    command: 'pnpm dev -- --host 127.0.0.1 --port 1420',
    url: 'http://127.0.0.1:1420',
    reuseExistingServer: !process.env.CI,
    timeout: 120_000,
  },
  use: {
    baseURL: 'http://127.0.0.1:1420',
    // Load pre-created storage state (generated by global-setup)
    // ESM-safe resolution of storage state path
    storageState: path.resolve(
      path.dirname(fileURLToPath(import.meta.url)),
      'tests/e2e/.auth-storage.json'
    ),
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        browserName: 'chromium',
      },
    },
  ],
  timeout: 60000,
  expect: {
    timeout: 10000,
  },
});
